package com.desafioitau.api.transferencia.exceptions.conta.exception;

public class ContaInternalErrorException extends ContaException {
    public ContaInternalErrorException(Throwable cause) {
        super(cause);
    }
}
