package com.desafioitau.api.transferencia.exceptions.notificacao.exception;

public class NotificacaoInternalErrorException extends NotificacaoException {
    public NotificacaoInternalErrorException(Throwable cause) {
        super(cause);
    }
}
